### ISSUE TITLE
failed to verify cert m2-cert.pem

### ISSUE THREAD

**Issue by dpashkevich** [mongrel2/mongrel2#205]
I checked out the latest master: https://github.com/zedshaw/mongrel2/commit/37323081d0ec8fbc27c8deb94d8abdebec1ff5b7
and trying to install it as described in the docs:

``` bash
make clean all && sudo make install
```

It seems to build fine, however a unit test fails:

``` bash
sh ./tests/runtests.sh
Running unit tests:
tests/bstr_tests PASS
tests/cache_tests PASS
ERROR in test tests/cert_tests:
----
RUNNING: ./tests/cert_tests
FAILED: failed to verify cert m2-cert.pem
Tests run: 1
make: *** [tests] Error 1
```

Sorry if that's too little details but I have no idea where to go from there...

**Comment by nanoscopic** [comment]
I have this same issue on the current master branch. The certificate has expired again. Since it is not explained clearly above, the m2-cert.pem file is located at /tests/ca/certs/m2-cert.pem.

To show the current expiration: openssl x509 -dates -noout -in m2-cert.pem
This shows: notAfter=Mar 13 05:57:52 2015 GMT. It expired 3 days ago.

As a lazy way to successfully build the project until this is fixed:
cd tests; mv cert_tests.c cert_tests.c.off; rm cert_tests; cd ..; make

**Comment by xinuc** [comment]
having this problem too :+1:

**Comment by pjkundert** [comment]
Until https://github.com/pjkundert/mongrel2, branch fix/polarssl is merged, this is going to keep happening.  In fact, it is guaranteed that any "snapshot" of mongrel2 will fail to compile as soon as the certificate expires.  The fix/polarssl branch permanently addresses this, by detecting if the SSL test *should* fail (ie. due to certificate expiry), and tests appropriately (while issuing a warning about the expired certificate).  Furthermore, the polarssl clone/patch/build procedure is cleaned up to be much safer, and allow for easily moving to newer versions of polarssl.   Give it a try, and lets get this fixed once and for all!

**Comment by tiago156** [comment]
same problem here.

RUNNING: ./tests/cert_tests
FAILED: failed to verify cert m2-cert.pem
Tests run: 1
make: *** [tests] Error 1

**Comment by jasom** [comment]
This is now fixed for good by @pjkundert's solution.

**Comment by AzadMemon** [comment]
I seem to be running into this problem still. I'm installing using brew. Here's my log:

==> Downloading https://github.com/zedshaw/mongrel2/releases/download/v1.9.1/mongrel2-v1.9.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/mongrel2-1.9.1.tar.gz
==> make all
----
RUNNING: ./tests/cert_tests
FAILED: failed to verify cert m2-cert.pem
Tests run: 1
make: *** [tests] Error 1

It seems to be pointing to the latest release (1.9.1).

**Comment by jasom** [comment]
This is fixed in git; there will be a 1.9.2 release soon

**Comment by AzadMemon** [comment]
@jasom Thanks a bunch!

**Comment by Grantley** [comment]
Hey guys - this is still failing. The cert refresh commentary you have also does not work (missing the openssl.cnf). Tried using a default config and I get "unable to load CA private key".

Any chance we can get this fixed?
